source 'https://rubygems.org'
ruby '2.3.0'
gem 'rails', '4.2.5.1'
gem 'pg', '~> 0.15'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'simple_form'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'autoprefixer-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
#gem 'therubyracer', '0.11.0'
gem 'responders'
gem 'i18n_alchemy', '~> 0.2.2'
gem 'enumerate_it'
gem 'devise'
gem 'immigrant'
gem 'has_scope'
gem "cocoon"
gem 'jquery-ui-rails'
gem 'rails4-autocomplete'
gem 'bootstrap-datepicker-rails'
gem 'validates_timeliness'
gem "carrierwave"
gem 'will_paginate', '~> 3.1.0'
gem 'will_paginate-bootstrap'
gem 'rails_12factor', group: :production
gem 'rails_log_stdout',           github: 'heroku/rails_log_stdout'
gem 'rails3_serve_static_assets', github: 'heroku/rails3_serve_static_assets'

